name: 🐛 Bug report
description: Create a report to help us improve profiler
title: "[BUG]: <concise title>"
labels: ['bug, untriaged']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect?
      placeholder: Tell us what happened and what you expected instead.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      value: |
         - Run `$ sudo profiler --list_interfaces`, and paste in the full output.

         - Run `$ sudo profiler --debug`, reproduce the issue, and paste in the full output.
      render: shell
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: |
        Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: input
    attributes:
      label: What version of the app are you using?
      description: |
        Please provide the app version where this issue occurred.
    validations:
      required: true
  - type: checkboxes
    id: contribs
    attributes:
      label: Contributions
      description: Please review our [developer documentation](https://github.com/WLAN-Pi/developers) before contributing.
      options:
        - label: I have read the contribution guidelines
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WLAN-Pi/.github/blob/main/code_of_conduct.md). 
      options:
        - label: I agree to follow WLAN Pi's Code of Conduct
          required: true