blank_issues_enabled: false
contact_links:
  - name: WLAN Pi Feedback
    url: https://github.com/WLAN-Pi/feedback/discussions
    about: Please ask and answer questions here. Don't open issues for usage questions.
