blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and help
    url: https://github.com/WLAN-Pi/feedback/discussions
    about: This issue tracker is not for support questions. Please refer to the discussions in the feedback repo instead.