name: Build and Archive Debian Package
on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  pull_request:
    paths:
      - 'debian/changelog'
env:
  debpackagename: wlanpi-profiler
jobs:
  format:
    name: Get formatted version for filename
    uses: WLAN-Pi/gh-workflows/.github/workflows/get-formatted-version-string.yml@main
  sbuild:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }} pkg
    uses: WLAN-Pi/gh-workflows/.github/workflows/sbuild-pkg.yml@main
    needs: format
    strategy:
      fail-fast: false
      matrix:
        distro: [bullseye,bookworm]
        arch: [arm64]
    with:
      distro: ${{ matrix.distro }}
      arch: ${{ matrix.arch }}
      pkg: ${{ env.debpackagename }}
      version: ${{ needs.format.outputs.version }}
  slack-workflow-status:
    if: ${{ always() && (! github.event.pull_request.head.repo.fork) }}
    name: Post Workflow Status to Slack
    needs:
      - sbuild
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-22.04' }}"
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
